//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dislicores_Proceso_5_Terceros_a_ClientesPOS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.105:8051/WSUNOEE_ODISEO_CE/WSUNOEE.ASMX")]
        public string Dislicores_Proceso_5_Terceros_a_ClientesPOS_WSUNOEE_WSUNOEE {
            get {
                return ((string)(this["Dislicores_Proceso_5_Terceros_a_ClientesPOS_WSUNOEE_WSUNOEE"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.54;Initial Catalog=Commercial_Effectiveness;User ID=sa;Pass" +
            "word=D1sl1c0r3s;Integrated Security=False")]
        public string strConexion {
            get {
                return ((string)(this["strConexion"]));
            }
            set {
                this["strConexion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WSREAL")]
        public string ConexionUNOEE {
            get {
                return ((string)(this["ConexionUNOEE"]));
            }
            set {
                this["ConexionUNOEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string CiaUNOEE {
            get {
                return ((string)(this["CiaUNOEE"]));
            }
            set {
                this["CiaUNOEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("servi.siesa")]
        public string UsuarioUNOEE {
            get {
                return ((string)(this["UsuarioUNOEE"]));
            }
            set {
                this["UsuarioUNOEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Servi2021")]
        public string ClaveUNOEE {
            get {
                return ((string)(this["ClaveUNOEE"]));
            }
            set {
                this["ClaveUNOEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PlanosIntegracionesGT\\")]
        public string planosGT {
            get {
                return ((string)(this["planosGT"]));
            }
            set {
                this["planosGT"] = value;
            }
        }
    }
}
